export const SET_PERSON_DATA = 'SET_PERSON_DATA';
export const GET_ERRORS = 'GET_ERRORS';
export const SORT_TABLE = 'SORT_TABLE';
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM';
export const CLOSE_UPDATE_FORM = 'CLOSE_UPDATE_FORM';
export const EDIT_PERSON_START = 'EDIT_PERSON_START';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';